# Generated by Django 5.0.7 on 2024-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=3, verbose_name='Foydalanuvchining tili')),
                ('tg_id', models.IntegerField(verbose_name='Foydalanuvchining tg id')),
            ],
            options={
                'verbose_name': 'Telegram foydalanuv ',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'db_table': 'tg_users',
            },
        ),
    ]
