# Generated by Django 5.0.7 on 2024-07-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_info', models.TextField(verbose_name="Umumiy ma'lumot")),
                ('history', models.TextField(verbose_name='Tarix')),
                ('mission', models.TextField(verbose_name='Missiya')),
                ('company_vision', models.TextField(verbose_name='Kompaniyaning qarashlari')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='company/photos', verbose_name='Rasm')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kompaniya ',
                'verbose_name_plural': 'Kompaniyalar',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_address', models.CharField(max_length=500, verbose_name='Kompaniya manzillari')),
                ('phone_number', models.CharField(max_length=500, verbose_name='Telefon raqamlar')),
                ('email', models.CharField(max_length=500, verbose_name='Elektron pochta')),
                ('social_networks', models.CharField(max_length=500, verbose_name='Ijtimoiy tarmoqlar')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Kontakt ',
                'verbose_name_plural': 'Kontaktlar',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Savol ',
                'verbose_name_plural': 'Savolar',
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='InvestApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=47, verbose_name="To'liq ismingiz")),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('advice', models.TextField(verbose_name='Batafsil maslahat')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Ariza ',
                'verbose_name_plural': 'Investorlar arizalari',
                'db_table': 'invest_applications',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_info', models.TextField(verbose_name="Moliyaviy ma'lumot")),
                ('reports', models.TextField(verbose_name='Hisobot')),
                ('future_plan', models.TextField(verbose_name='Kelajak rejalari')),
                ('contact_info', models.CharField(max_length=250, verbose_name="Aloqa ma'lumoti")),
                ('image', models.ImageField(blank=True, null=True, upload_to='investors/photos', verbose_name='Rasm')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Investor ',
                'verbose_name_plural': 'Investorlar',
                'db_table': 'investors',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('body', models.TextField(verbose_name="Batafsil ma'lumot")),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/photos', verbose_name='Rasm')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Yangilik ',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_opportunities', models.CharField(max_length=1000, verbose_name='Hamkorlik imkoniyatlari')),
                ('partnership_programs', models.CharField(max_length=1000, verbose_name='Hamkorlik dasturlari')),
                ('conditions', models.CharField(max_length=1000, verbose_name='Shartlar')),
                ('contact_info', models.CharField(max_length=1000, verbose_name="Aloqa ma'lumotlari")),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner/photos', verbose_name='Rasm')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Hamkor ',
                'verbose_name_plural': 'Hamkorlar',
                'db_table': 'partners',
            },
        ),
        migrations.CreateModel(
            name='PartnershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=70, verbose_name="To'liq ismingiz")),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon raqam')),
                ('advice', models.TextField(verbose_name='Batafsil maslahat')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Yaratilgan Vaqt')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Ozgartirilgan vaqt')),
            ],
            options={
                'verbose_name': 'Ariza ',
                'verbose_name_plural': 'Hamkorlar arizalari',
                'db_table': 'partner_applications',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.TextField(verbose_name='Servis xizmati')),
                ('product', models.TextField(verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Servis ',
                'verbose_name_plural': 'Servislar',
                'db_table': 'services',
            },
        ),
    ]
