# Generated by Django 5.0.7 on 2024-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_company_vision_ru_company_company_vision_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image_url',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investor',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
