# Generated by Django 5.0.7 on 2024-07-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_image_url_investor_image_url_news_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
