# Generated by Django 5.0.7 on 2024-07-26 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['created_at'], 'verbose_name': 'Kompaniya ', 'verbose_name_plural': 'Kompaniyalar'},
        ),
    ]
