# Generated by Django 5.0.7 on 2024-07-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': "Moliyaviy ma'lumot ", 'verbose_name_plural': "Moliyaviy ma'lumotlar"},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Hamkorlikning afzalliklarini ', 'verbose_name_plural': 'Hamkorlikning afzalliklari'},
        ),
    ]
