# Generated by Django 5.0.7 on 2024-07-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_investor_options_alter_partner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': "Moliyaviy ma'lumot haqida ", 'verbose_name_plural': "Moliyaviy ma'lumotlar"},
        ),
    ]
